name: trading_app
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.3

flutter:
  uses-material-design: true
